/**
 * Marcas que trabajamos, portado de victorso-demo/data.js.
 * Shopify no tiene un objeto "marca" nativo (el vendor del producto es
 * el campo mas cercano), asi que esto vive como contenido editorial
 * propio: nombre, logo, web oficial y una descripcion corta. El conteo
 * real de productos por marca se consulta en vivo contra la Storefront
 * API usando el nombre como filtro de vendor.
 */
export type Brand = {
  name: string;
  slug: string;
  website: string | null;
  logo?: string;
  featured?: boolean;
  description: string;
};

export const BRANDS: Brand[] = [
  {name: 'Pioneer DJ', slug: 'pioneer-dj', featured: true, website: 'https://www.pioneerdj.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/165x83_q100_png9_cr0_fix1/pioneer-dj.png',
    description: 'El estándar mundial en cabinas de DJ profesionales. Pioneer DJ equipa las salas y festivales más importantes del planeta, y es la marca en la que más confiamos en Victor So Professional.'},
  {name: 'AlphaTheta', slug: 'alphatheta', featured: true, website: 'https://www.alphatheta.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosmarcas2/165x83_q100_png9_cr0_fix1/AlphaTheta_logo_Horizontal_k.jpg',
    description: 'La nueva marca del grupo Pioneer DJ / TAG Sound, enfocada en innovación para DJs: sistemas todo en uno, monitores de estudio y equipos portátiles de última generación.'},
  {name: 'Walkasse', slug: 'walkasse', featured: true, website: 'https://www.walkasse.com', logo: '/assets/logo-walkasse.jpg',
    description: 'Fabricante especializado en flight-cases y bolsas de transporte a medida, pensados para proteger equipos de sonido e iluminación en giras y eventos.'},
  {name: 'RCF', slug: 'rcf', featured: true, website: 'https://www.rcf.it', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/logo_rcf.jpg',
    description: 'Fabricante italiano con más de 70 años de historia en sonido profesional, presente en salas de conciertos, teatros y eventos en directo de todo el mundo.'},
  {name: 'Yamaha', slug: 'yamaha', featured: true, website: 'https://www.yamaha.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/285_Victorso.jpg',
    description: 'Uno de los grandes nombres de la electrónica musical, con altavoces y equipos de sonido conocidos por su fiabilidad y calidad de fabricación.'},
  {name: 'QSC', slug: 'qsc', featured: true, website: 'https://www.qsc.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/qsc_logo.jpg',
    description: 'Marca americana referente en altavoces activos y sistemas de sonido para instalaciones fijas, salas de conciertos y giras profesionales.'},
  {name: 'Rode', slug: 'rode', featured: true, website: 'https://www.rode.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/rode_logo.png',
    description: 'Fabricante australiano de micrófonos de estudio y grabación, muy valorado por creadores de contenido y estudios por su calidad de sonido y precio.'},
  {name: 'Focusrite', slug: 'focusrite', featured: true, website: 'https://focusrite.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/focusrite_logo.jpg',
    description: 'Interfaces de audio de referencia para producción musical en casa y en estudio, con la gama Scarlett como estándar de entrada al mundo profesional.'},
  {name: 'Sennheiser', slug: 'sennheiser', featured: true, website: 'https://www.sennheiser.com', logo: 'https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosmarcas2/165x83_q100_png9_cr0_fix1/senheiser.png',
    description: 'Marca alemana centenaria en audio profesional, reconocida mundialmente por sus auriculares y micrófonos de altísima fidelidad.'},
  {name: 'Alesis', slug: 'alesis', website: 'https://www.alesis.com',
    description: 'Marca americana especializada en baterías electrónicas, teclados, controladores MIDI y equipos de grabación.'},
  {name: 'Allen & Heath', slug: 'allen-heath', website: 'https://www.allen-heath.com',
    description: 'Fabricante británico de mesas de mezclas analógicas y digitales para directo, instalación y DJ, con más de 50 años de historia.'},
  {name: 'Antelope Audio', slug: 'antelope-audio', website: 'https://en.antelopeaudio.com', logo: '/assets/logos/antelope-audio.jpg',
    description: 'Especialista en interfaces de audio, relojes maestros y micrófonos modelados de alta gama para estudio.'},
  {name: 'Arkaos', slug: 'arkaos', website: 'https://vj.arkaos.com',
    description: 'Software de referencia para VJs, servidores de medios y mapping de LED usado en conciertos y eventos desde 1996.'},
  {name: 'Audient', slug: 'audient', website: 'https://audient.com', logo: '/assets/logos/audient.png',
    description: 'Fabricante británico de interfaces de audio, consolas y preamplificadores muy valorados en estudios de grabación.'},
  {name: 'Audio-Technica', slug: 'audio-technica', website: 'https://www.audio-technica.com', logo: '/assets/logos/audio-technica.svg',
    description: 'Fabricante japonés de micrófonos, auriculares y giradiscos con décadas de prestigio en audio profesional y doméstico.'},
  {name: 'Audiolab', slug: 'audiolab', website: 'https://www.audiolab.co.uk',
    description: 'Marca británica de alta fidelidad especializada en amplificadores, reproductores y DACs para audiófilos.'},
  {name: 'Auralex', slug: 'auralex', website: 'https://auralex.com',
    description: 'Líder en tratamiento acústico para estudios: espuma acústica, trampas de graves y difusores.'},
  {name: 'AVID', slug: 'avid', website: 'https://www.avid.com', logo: '/assets/logos/avid.png',
    description: 'Creadores de Pro Tools, el estándar de la industria en estaciones de trabajo de audio digital (DAW).'},
  {name: 'Bitwig', slug: 'bitwig', website: 'https://www.bitwig.com', logo: '/assets/logos/bitwig.svg',
    description: 'Estación de trabajo de audio digital alemana pensada tanto para producción en estudio como para actuación en directo.'},
  {name: 'Dbx', slug: 'dbx', website: 'https://dbxpro.com', logo: '/assets/logos/dbx.png',
    description: 'Marca americana de referencia en procesadores de dinámica: compresores, limitadores y puertas de ruido.'},
  {name: 'DJBAG.PRO', slug: 'djbag-pro', website: null,
    description: 'Marca especializada en mochilas y bolsas de transporte diseñadas por DJs para proteger controladoras y auriculares en la carretera.'},
  {name: 'Electro-Voice', slug: 'electro-voice', website: 'https://www.electrovoice.com', logo: '/assets/logos/electro-voice.svg',
    description: 'Fabricante americano fundado en 1930, referencia en altavoces y micrófonos para sonido en directo e instalaciones.'},
  {name: 'GAPLASA', slug: 'gaplasa', website: 'https://gaplasapro.com', logo: '/assets/logos/gaplasa.jpg',
    description: 'Distribuidor español de sonido profesional, representante de marcas como Bose Professional y Clockaudio.'},
  {name: 'Gravity', slug: 'gravity', website: null,
    description: 'Marca del grupo Adam Hall especializada en soportes y trípodes para altavoces, micrófonos, teclados e iluminación.'},
  {name: 'Gretsch', slug: 'gretsch', website: 'https://www.gretsch.com',
    description: 'Firma histórica americana de guitarras y baterías, con un sonido característico reconocido desde hace más de un siglo.'},
  {name: 'Konig & Meyer', slug: 'konig-meyer', website: 'https://www.k-m.de', logo: '/assets/logos/konig-meyer.png',
    description: 'Fabricante alemán con más de 75 años de experiencia en soportes para micrófonos, altavoces, teclados e instrumentos.'},
  {name: 'korg', slug: 'korg', website: 'https://www.korg.com',
    description: 'Compañía japonesa pionera en sintetizadores, pianos digitales, afinadores y procesadores de audio.'},
  {name: 'KS technology', slug: 'ks-technology', website: 'https://ks-audio.com',
    description: 'Fabricante alemán de sistemas de altavoces profesionales para salas, clubes, instalaciones y grandes eventos.'},
  {name: 'M-AUDIO', slug: 'm-audio', website: 'https://www.m-audio.com', logo: '/assets/logos/m-audio.jpg',
    description: 'Marca de interfaces de audio, teclados MIDI y monitores de estudio orientada a la producción musical doméstica y profesional.'},
  {name: 'Magma', slug: 'magma', website: 'https://www.magma-bags.de', logo: '/assets/logos/magma.png',
    description: 'Fabricante alemán de bolsas y flight-cases a medida para controladoras, mesas de mezclas y equipos de DJ.'},
  {name: 'MAGNETRON S.A.', slug: 'magnetron', website: 'https://www.magnetron.es',
    description: 'Distribuidor español de audio profesional, representante de marcas como Sennheiser, Neumann y FBT.'},
  {name: 'Native Instruments', slug: 'native-instruments', website: 'https://www.native-instruments.com', logo: '/assets/logos/native-instruments.svg',
    description: 'Referencia en software y hardware para producción musical y DJ, creadores de Traktor y Komplete.'},
  {name: 'Neumann', slug: 'neumann', website: 'https://www.neumann.com', logo: '/assets/logos/neumann.png',
    description: 'Fabricante alemán de micrófonos de estudio desde 1928, sinónimo de calidad de grabación de referencia mundial.'},
  {name: 'Neutrik', slug: 'neutrik', website: 'https://www.neutrik.com', logo: '/assets/logos/neutrik.svg',
    description: 'Líder mundial en conectores de audio profesional, como los conectores XLR y speakON.'},
  {name: 'OQAN', slug: 'oqan', website: 'https://oqanmusic.com', logo: '/assets/logos/oqan.png',
    description: 'Marca española de instrumentos musicales y accesorios de sonido con una relación calidad-precio muy competitiva.'},
  {name: 'Palmer', slug: 'palmer', website: 'https://www.palmer-germany.com', logo: '/assets/logos/palmer.png',
    description: 'Fabricante alemán conocido por sus cajas DI y equipos de re-amplificación para estudio y directo.'},
  {name: 'PD-Connex', slug: 'pd-connex', website: null,
    description: 'Gama de cables y conectores de audio, iluminación y alimentación para uso profesional y doméstico.'},
  {name: 'PlayDifferently', slug: 'playdifferently', website: 'https://playdifferently.org', logo: '/assets/logos/playdifferently.jpg',
    description: 'Marca creada por Andy Rigby-Jones junto a Richie Hawtin, autora del icónico mixer analógico MODEL 1.'},
  {name: 'Presonus', slug: 'presonus', website: 'https://www.presonus.com', logo: '/assets/logos/presonus.png',
    description: 'Fabricante americano de interfaces de audio, mezcladores y monitores, creadores del DAW Studio One.'},
  {name: 'RANE_DJ', slug: 'rane', website: 'https://www.rane.com', logo: '/assets/logos/rane.png',
    description: 'Marca de referencia en mixers y controladoras DJ de altísima gama, utilizada por DJs profesionales de todo el mundo.'},
  {name: 'RME', slug: 'rme', website: 'https://rme-audio.de',
    description: 'Fabricante alemán de interfaces de audio y conversores reconocido por su estabilidad y latencia mínima.'},
  {name: 'Roline', slug: 'roline', website: 'https://theroline.com', logo: '/assets/logos/roline.jpg',
    description: 'Marca de cables y accesorios de conectividad para instalaciones audiovisuales y de red.'},
  {name: 'Samson', slug: 'samson', website: 'https://samsontech.com', logo: '/assets/logos/samson.jpg',
    description: 'Fabricante americano de micrófonos, sistemas inalámbricos y monitores para directo y estudio.'},
  {name: 'Softube', slug: 'softube', website: 'https://www.softube.com', logo: '/assets/logos/softube.svg',
    description: 'Compañía sueca de plugins de audio de altísima calidad, en colaboración con marcas históricas como SSL o Tube-Tech.'},
  {name: 'Sonifex', slug: 'sonifex', website: 'https://www.sonifex.co.uk', logo: '/assets/logos/sonifex.png',
    description: 'Fabricante británico de equipos de audio para radio y televisión desde 1969.'},
  {name: 'Sony', slug: 'sony', website: 'https://pro.sony', logo: '/assets/logos/sony.svg',
    description: 'Multinacional japonesa con una amplia gama de soluciones de audio profesional para producción y directo.'},
  {name: 'Stanton', slug: 'stanton', website: 'https://www.stantondj.com',
    description: 'Marca histórica del mundo DJ, pionera en giradiscos, cápsulas y mixers para scratch y turntablism.'},
  {name: 'Superlux', slug: 'superlux', website: 'https://en.superlux.com.tw',
    description: 'Fabricante taiwanés de micrófonos y auriculares con una excelente relación calidad-precio.'},
  {name: 'Synq', slug: 'synq', website: 'https://synq-audio.com', logo: '/assets/logos/synq.png',
    description: 'Marca europea de equipos de sonido para instalación y DJ: amplificadores, altavoces y mixers.'},
  {name: 'Tannoy', slug: 'tannoy', website: 'https://www.tannoy.com', logo: '/assets/logos/tannoy.svg',
    description: 'Fabricante británico de altavoces fundado en 1926, con un legado reconocido en sonorización profesional.'},
  {name: 'Tascam', slug: 'tascam', website: 'https://tascam.com', logo: '/assets/logos/tascam.svg',
    description: 'Marca japonesa histórica en grabadores multipista y de campo para estudio, broadcast y producción audiovisual.'},
  {name: 'Tc electronic', slug: 'tc-electronic', website: 'https://www.tcelectronic.com', logo: '/assets/logos/tc-electronic.svg',
    description: 'Fabricante danés de efectos, procesadores e interfaces de audio de gran prestigio entre músicos y estudios.'},
  {name: 'Tc Helicon', slug: 'tc-helicon', website: 'https://www.tc-helicon.com',
    description: 'Especialista en procesadores vocales, armonizadores y micrófonos para cantantes en directo y estudio.'},
  {name: 'Technics', slug: 'technics', website: 'https://www.technics.com', logo: '/assets/logos/technics.svg',
    description: 'Marca japonesa creadora del legendario giradiscos SL-1200, estándar mundial del DJ profesional.'},
  {name: 'Tecshow', slug: 'tecshow', website: null,
    description: 'Marca de equipos de sonido activo e iluminación DMX orientada al mercado profesional y de eventos.'},
  {name: 'teenage engineering', slug: 'teenage-engineering', website: 'https://teenage.engineering',
    description: 'Diseñadora sueca de sintetizadores y grooveboxes de culto, reconocida por su diseño minimalista y su sonido único.'},
  {name: 'Turbosound', slug: 'turbosound', website: 'https://www.turbosound.com',
    description: 'Fabricante de altavoces profesionales para sonido en directo, instalaciones y sistemas de línea de array.'},
  {name: 'Udg', slug: 'udg', website: 'https://udggear.com',
    description: "Marca líder en bolsas y maletas de transporte para DJs, conocida como 'Ultimate DJ Gear'."},
  {name: 'Universal audio', slug: 'universal-audio', website: 'https://www.uaudio.com', logo: '/assets/logos/universal-audio.png',
    description: 'Referencia mundial en interfaces de audio y plugins UAD con emulaciones analógicas de equipos de estudio clásicos.'},
  {name: 'work', slug: 'work-pro', website: 'https://www.workpro.es', logo: '/assets/logos/work-pro.png',
    description: 'Marca de Equipson especializada en altavoces y sistemas de sonido profesional para instalación fija y portátil.'},
  {name: 'ZENTRALMEDIA', slug: 'zentralmedia', website: 'https://www.zentralmedia.com',
    description: 'Distribuidor español de tecnología musical, audio profesional, DJ e iluminación para instalación.'},
  {name: 'Zomo', slug: 'zomo', website: 'https://www.zomo.de', logo: '/assets/logos/zomo.png',
    description: 'Marca alemana especializada en bolsas, flight-cases y accesorios de transporte para equipos de DJ.'},
];

export function findBrand(slug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === slug);
}
